#!/usr/bin/env bash
# SPDX-FileCopyrightText: PIConGPU contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

# search recursive inside a folder if the keyword `__global__` is used
# @param $1 path to the folder
# @result 0 if keyword is not found else 1

folderName=$1
result=`grep -rn "__global__" $folderName`
if [ $? -eq 0 ] ; then
    echo "Not allowed keyword __global__ found in the following files:" >&2
    echo "$result" | cut -f1-2 -d":" >&2
    exit 1
fi
exit 0
