#!/usr/bin/env bash
#
# Copyright 2016-2021 Axel Huebl
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

# search recursive inside a folder if a file contains tabs
#
# @result 0 if no files are found, else 1
#

ok=0
files=()

pattern="\.def$|\.h$|\.cpp$|\.cu$|\.hpp$|\.tpp$|\.kernel$|\.loader$|"\
"\.param$|\.unitless$|\.sh$|\.bash$|\.cfg$|\.tpl$|\.conf$|"\
"\.awk$|\.gnuplot$|\.cmake$|\.profile$|\.example$|\.py$|"\
"\.md$|cmakeFlags|CMakeLists\.txt|src/tools/bin"

for i in $(find . \
                -not -path "./.git/*" \
                -not -path "./thirdParty/*" \
                -not -path "./buildsystem/CompileSuite/autoTests/get_work.sh" \
                -type f | \
           grep -P "${pattern}")
do
  grep -q -P "\t" $i
  if [ $? -eq 0 ]
  then
    files+=($i)
    echo "$i contains TABs instead of spaces!"
    ok=1
  fi
done

if [ $ok -ne 0 ]
then
  echo ""
  echo "SUMMARY"
  echo "-------"
  echo "Run the following command(s) on the above files to replace your TABs"
  echo "with four white spaces:"
  echo ""
  echo "GNU_SED=\$(sed --help >/dev/null 2>&1 && { echo 1; } || { echo 0; })"
  echo "[[ \${GNU_SED} -eq 1 ]] && REPLACE=\"sed -i 's/\t/\ \ \ \ /g'\" || REPLACE=\"sed -i '' -E 's/\$(printf '\t')/\ \ \ \ /g'\""
  for i in ${files[@]}
  do
    echo "eval \"\${REPLACE}\" $i"
  done
fi

exit $ok
