#!/usr/bin/env bash
# SPDX-FileCopyrightText: PIConGPU contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

# search recursive inside the `$1` folder if a file is using the
# wrong include brackets "..." instead of <...> to include external library files
#
# @param $1 path to the folder
# @param $2 prefix of the extern library e.g pmacc, boost
# @result 0 if no files are found, else 1

folderName=$1
keyword=$2

ok=0
files=()

pattern="\.def$|\.h$|\.cpp$|\.cu$|\.hpp$|\.tpp$|\.kernel$|\.loader$|"\
"\.param$|\.unitless$"

for i in $(find $folderName \
    -not -path "./.git/*" \
    -type f | \
    grep -P "${pattern}")
do
    grep -q "\\\\${keyword}" $i
    if [ $? -eq 0 ]
    then
        files+=($i)
        echo "$i uses \\${keyword} instead of @$keyword"
        ok=1
    fi
done

if [ $ok -ne 0 ]
then
    echo ""
    echo "SUMMARY"
    echo "-------"
    echo "Run the following command(s) on the above files to update your style:"
    echo ""
    for i in ${files[@]}
    do
        echo "sed -i 's/\\\\${keyword}/@${keyword}/g' $i"
    done
fi

exit $ok
