#!/usr/bin/env bash

# SPDX-FileCopyrightText: Axel Huebl, Rene Widera, Richard Pausch
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

# test all pushers in 3D and 2D
# Boris Pusher
flags[0]=""

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_DIMENSION=DIM2'"

  # Vay Pusher
  flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_PARTICLEPUSHER=Vay'"
  flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_PARTICLEPUSHER=Vay;-DPARAM_DIMENSION=DIM2'"
  # Photon Pusher
  flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_PARTICLEPUSHER=Photon'"
  flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_PARTICLEPUSHER=Photon;-DPARAM_DIMENSION=DIM2'"
  # does not support 2D
  # Reduced Landau Lifshitz Pusher
  flags[6]="-DPARAM_OVERWRITES:LIST='-DPARAM_PARTICLEPUSHER=ReducedLandauLifshitz'"
  flags[7]="-DPARAM_OVERWRITES:LIST='-DPARAM_PARTICLEPUSHER=ReducedLandauLifshitz;-DPARAM_DIMENSION=DIM2'"
fi

################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
