"""
This file is part of PIConGPU.
Copyright 2026 PIConGPU contributors
License: GPLv3+
"""

import os
import re
import tempfile
from unittest import TestCase

from picongpu import picmi
from picongpu.picmi import constants
from picongpu.picmi.diagnostics import EnergyHistogram, TimeStepSpec


class TestEnergyHistogram(TestCase):
    @staticmethod
    def __get_species():
        return picmi.Species(name="e", particle_type="electron")

    def __get_histogram(self, species, max_energy_keV):
        return EnergyHistogram(
            species=species,
            period=TimeStepSpec[:16:2],
            bin_count=32,
            min_energy=0.0,
            max_energy=max_energy_keV * constants.keV,
        )

    def test_si_units_converted_to_kev_for_backend(self):
        # energies are given in SI (joule) and must be passed to the backend in keV
        histogram = self.__get_histogram(self.__get_species(), max_energy_keV=42.0)

        converted = histogram.get_as_pypicongpu(time_step_size=1, num_steps=17)

        assert converted.type_energyhistogram is True
        assert converted.min_energy + converted.max_energy - 42.0 < 1e-14
        assert converted.bin_count == 32

    def test_min_energy_converted(self):
        histogram = EnergyHistogram(
            species=self.__get_species(),
            period=TimeStepSpec[:16:2],
            bin_count=32,
            min_energy=7.0 * constants.keV,
            max_energy=42.0 * constants.keV,
        )

        converted = histogram.get_as_pypicongpu(time_step_size=1, num_steps=17)

        assert abs(converted.min_energy - 7.0) < 1e-14
        assert abs(converted.max_energy - 42.0) < 1e-14

    def test_invalid_range_rejected(self):
        with self.assertRaises(ValueError):
            histogram = EnergyHistogram(
                species=self.__get_species(),
                period=TimeStepSpec[:16:2],
                bin_count=32,
                min_energy=42e-16,
                max_energy=7.0 * constants.keV,
            )
            histogram.get_as_pypicongpu(time_step_size=1, num_steps=17)

    def test_rendered_n_cfg_uses_kev(self):
        # the command line generated by the template must carry the keV value
        grid = picmi.Cartesian3DGrid(
            number_of_cells=[32, 32, 32],
            lower_bound=[0, 0, 0],
            upper_bound=[3.2e-6, 3.2e-6, 3.2e-6],
            lower_boundary_conditions=["open", "open", "open"],
            upper_boundary_conditions=["open", "open", "open"],
        )
        solver = picmi.ElectromagneticSolver(method="Yee", grid=grid, cfl=1.0)
        sim = picmi.Simulation(time_step_size=None, max_steps=17, solver=solver)
        electrons = picmi.Species(
            name="e",
            particle_type="electron",
            initial_distribution=picmi.UniformDistribution(density=1e20),
        )
        sim.add_species(electrons, picmi.PseudoRandomLayout(n_macroparticles_per_cell=2))
        sim.diagnostics = [self.__get_histogram(electrons, max_energy_keV=42.0)]

        with tempfile.TemporaryDirectory() as outdir:
            sim.write_input_file(outdir, exist_ok=True)

            n_cfg = os.path.join(outdir, "etc", "picongpu", "N.cfg")
            if not os.path.isfile(n_cfg):
                candidates = [
                    os.path.join(root, name) for root, _, names in os.walk(outdir) for name in names if name == "N.cfg"
                ]
                assert candidates, f"no rendered N.cfg found under {outdir}"
                n_cfg = candidates[0]

            with open(n_cfg) as cfg:
                content = cfg.read()

        match = re.search(r"--e_energyHistogram\.maxEnergy (\S+)", content)
        assert match is not None, "energyHistogram options not found in rendered N.cfg"
        assert abs(float(match.group(1)) - 42.0) < 1e-11
