# This file is part of PIConGPU.
# Copyright 2025 PIConGPU contributors
# Authors: Pawel Ordyna
# License: GPLv3+

[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "picongpu"
version = "0.9.0.dev"
description = "Python package for PIConGPU"
license = "GPL-3.0-or-later"
# Our hand-rolled type-safety infrastructure is getting in the way of 3.14.
# Planning to fix (and remove this again) in the near future:
requires-python = ">=3.11,<3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
# dependecies list generated with
# https://gist.github.com/pordyna/ff27ce949a8e944fe30252f47b5b831f
dependencies = [
  "cwltool",
  "h5py",
  "imageio",
  "jsonschema>=4.23",
  "matplotlib",
  # temporary bug-fix branch, should point to an upcoming release including this in the future:
  "moosetash @ git+https://github.com/chillenzer/moosetash.git@fix-none-handling",
  "mpmath>=1.3",
  "numpy>=1.26.2",
  "openpmd-api>=0.16.1",
  "pandas>=2.2.3",
  "particle>=0.25.1",
  "periodictable>=1.7.1",
  # This commit hash points to branch: pydantic-refactoring-picongpu-base,
  # so we don't loose it if someone force-pushes to the main feature branch.
  "picmistandard @ git+https://github.com/chillenzer/picmi.git@c1d662238fc6642ca683826df688ccca12ed3765",
  "pillow",
  "pint",
  "pydantic>=2.6.4",
  "pyyaml",
  "questionary>=2",
  "referencing>=0.35.1",
  "roc-validator",
  # Temporarily choosing the master here
  # because the latest release doesn't yet support RO-Crate v1.2
  # and it doesn't seem reasonable to build a new feature on top of an outdated standard.
  "rocrate @ git+https://github.com/ResearchObject/ro-crate-py@master",
  "scipy>=1.12",
  "sympy>=1.14",
  "tomli-w>=1.2",
]

optional-dependencies.test = [ "pytest>=9" ]

scripts.picrc-builder = "picongpu.picrc_builder:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [ "picongpu" ]

[tool.hatch.build.targets.wheel.force-include]
"../../include" = "picongpu/core/include"
"../../etc" = "picongpu/core/etc"
"../../bin" = "picongpu/core/bin"
"../../src/tools/bin" = "picongpu/core/bin"
"../../share/picongpu/examples" = "picongpu/core/share/picongpu/examples"
"../../thirdParty" = "picongpu/core/thirdParty"

[tool.hatch.build.targets.sdist]
packages = [ "picongpu" ]
[tool.hatch.build.targets.sdist.force-include]
"../../include" = "picongpu/core/include"
"../../etc" = "picongpu/core/etc"
"../../bin" = "picongpu/core/bin"
"../../src/tools/bin" = "picongpu/core/bin"
"../../share/picongpu/examples" = "picongpu/core/share/picongpu/examples"
"../../thirdParty" = "picongpu/core/thirdParty"

[tool.pytest.ini_options]
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  "compiling: tests that compile PIConGPU simulations",
  "end_to_end: end-to-end simulation tests",
]
filterwarnings = [ "error" ]
