# This file is part of PIConGPU.
# Copyright 2025 PIConGPU contributors
# Authors: Pawel Ordyna
# License: GPLv3+

[build-system]
build-backend = "uv_build"

requires = [ "uv-build>=0.10.9,<0.11" ]

[project]
name = "picongpu"
# should be always identical with PIConGPU version
version = "0.9.0.dev"
description = "Python package for PIConGPU"
license = "GPL-3.0-or-later"
# Our hand-rolled type-safety infrastructure is getting in the way of 3.14.
# Planning to fix (and remove this again) in the near future:
requires-python = ">=3.11,<3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
# dependecies list generated with
# https://gist.github.com/pordyna/ff27ce949a8e944fe30252f47b5b831f
dependencies = [
  "h5py",
  "imageio",
  "jsonschema>=4.23",
  "matplotlib",
  # temporary bug-fix branch, should point to an upcoming release including this in the future:
  "moosetash @ git+https://github.com/chillenzer/moosetash.git@fix-none-handling",
  "mpmath>=1.3",
  "numpy>=1.26.2",
  "openpmd-api>=0.16.1",
  "pandas>=2.2.3",
  "particle>=0.25.1",
  "periodictable>=1.7.1",
  "picmistandard>=0.27",
  "pillow",
  "pint",
  "pydantic>=2.6.4",
  "referencing>=0.35.1",
  "scipy>=1.12",
  "sympy>=1.14",
  "tomli-w>=1.2",
  "typeguard>=4.2.1",
]

optional-dependencies.test = [ "pytest>=9" ]

[tool.pytest.ini_options]
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  "compiling: tests that compile PIConGPU simulations",
  "end_to_end: end-to-end simulation tests",
]
filterwarnings = [ "error" ]

[tool.uv.build-backend]
module-name = "picongpu"
module-root = ""
namespace = true
