#!/usr/bin/env bash

# SPDX-FileCopyrightText: Axel Huebl, Rene Widera, Richard Pausch, Jakob Trojok
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]=""

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_LASERPROFILE=GaussianBeamWithFreeEnvelope;-DPARAM_IONIZATIONCURRENT=EnergyConservation'"
  flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_LASERPROFILE=GaussianBeam'"
fi

################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
