#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: Axel Huebl, Rene Widera, Richard Pausch, Klaus Steiniger
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

# test all pushers in 3D and 2D
# Boris Pusher
flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_CURRENTSOLVER=EZ;-DPARAM_VX=1;-DPARAM_VY=0;-DPARAM_VZ=0'"

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_CURRENTSOLVER=Esirkepov;-DPARAM_VX=1;-DPARAM_VY=0;-DPARAM_VZ=0'"

  flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_CURRENTSOLVER=EZ;-DPARAM_VX=1;-DPARAM_VY=1;-DPARAM_VZ=0'"
  flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_CURRENTSOLVER=EZ;-DPARAM_VX=1;-DPARAM_VY=1;-DPARAM_VZ=1'"

  flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_CURRENTSOLVER=Esirkepov;-DPARAM_VX=1;-DPARAM_VY=1;-DPARAM_VZ=0'"
  flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_CURRENTSOLVER=Esirkepov;-DPARAM_VX=1;-DPARAM_VY=1;-DPARAM_VZ=1'"
fi



################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
