#!/usr/bin/env bash

# SPDX-FileCopyrightText: Axel Huebl, Rene Widera, Pawel Ordyna
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc'"
flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=1'"
flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=0'"
# test support for 32bit precision
flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_COLLISION_PRECISION=float_32;-DPARAM_PRECISION=precision32Bit'"
# test support for mixed precision
flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_PRECISION=precision32Bit'"

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  # constant log
  flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner1000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc'"
  flags[6]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc'"
  # dynamic  log (both)
  flags[7]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner1000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=1'"
  flags[8]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=1'"
  # dynamic  log (only inter)
  flags[9]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner1000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=0'"
  flags[10]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=0'"
fi

################################################################################
# execution

case "$1" in
-l)
  echo ${#flags[@]}
  ;;
-ll)
  for f in "${flags[@]}"; do echo $f; done
  ;;
*)
  echo -n ${flags[$1]}
  ;;
esac
