#!/usr/bin/env bash
#
# Copyright 2013-2022 Axel Huebl, Rene Widera, Pawel Ordyna
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

# constant log
flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc'"
flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner1000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc'"
flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc'"
# dynamic  log (both)
flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=1'"
flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner1000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=1'"
flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=1'"
# dynamic  log (only inter)
flags[6]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=0'"
flags[7]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner1000ppc;-DPARAM_START_ELECTRONS=Corner5000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=0'"
flags[8]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_DYNAMIC_LOG_INTER=1;-DPARAM_DYNAMIC_LOG_INTRA=0'"
# test support for 32bit precision
flags[9]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_COLLISION_PRECISION=float_32;-DPARAM_PRECISION=precision32Bit'"
# test support for mixed precision
flags[10]="-DPARAM_OVERWRITES:LIST='-DPARAM_START_IONS=Corner5000ppc;-DPARAM_START_ELECTRONS=Corner1000ppc;-DPARAM_PRECISION=precision32Bit'"

################################################################################
# execution

case "$1" in
-l)
  echo ${#flags[@]}
  ;;
-ll)
  for f in "${flags[@]}"; do echo $f; done
  ;;
*)
  echo -n ${flags[$1]}
  ;;
esac
