#!/usr/bin/env bash

# SPDX-FileCopyrightText: Axel Huebl, Rene Widera, Pawel Ordyna
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.2;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignFastDrift'"

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.001;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift;-DPARAM_DYNAMIC_LOG=1'"
  flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.001;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift'"
  flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=3.333333;-DPARAM_DELTA_T=0.0002;-DPARAM_CHARGE_IONS=IonCharge3;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift'"
  flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.2;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignFastDrift;-DPARAM_DYNAMIC_LOG=1'"
  flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=3.333333;-DPARAM_DELTA_T=0.0002;-DPARAM_CHARGE_IONS=IonCharge3;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift;-DPARAM_DYNAMIC_LOG=1'"
fi
################################################################################
# execution

case "$1" in
-l)
  echo ${#flags[@]}
  ;;
-ll)
  for f in "${flags[@]}"; do echo $f; done
  ;;
*)
  echo -n ${flags[$1]}
  ;;
esac
