#!/usr/bin/env bash
#
# Copyright 2013-2023 Axel Huebl, Rene Widera, Pawel Ordyna
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.2;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignFastDrift'"
flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.001;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift'"
flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=3.333333;-DPARAM_DELTA_T=0.0002;-DPARAM_CHARGE_IONS=IonCharge3;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift'"
flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.2;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignFastDrift;-DPARAM_DYNAMIC_LOG=1'"
flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=10.0;-DPARAM_DELTA_T=0.001;-DPARAM_CHARGE_IONS=IonCharge1;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift;-DPARAM_DYNAMIC_LOG=1'"
flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_DENSITY_RATIO_IONS=3.333333;-DPARAM_DELTA_T=0.0002;-DPARAM_CHARGE_IONS=IonCharge3;-DPARAM_DRIFT_ELECTRONS=AssignSlowDrift;-DPARAM_DYNAMIC_LOG=1'"
################################################################################
# execution

case "$1" in
-l)
  echo ${#flags[@]}
  ;;
-ll)
  for f in "${flags[@]}"; do echo $f; done
  ;;
*)
  echo -n ${flags[$1]}
  ;;
esac
