#!/usr/bin/env bash

# SPDX-FileCopyrightText: Axel Huebl, Rene Widera, Richard Pausch
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

# test all pushers in 3D and 2D
# Boris Pusher
# 0.825e-12 = Period of a gyro-motion in s for an electron with beta=0.5 in B=50T
# units: seconds
flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_DT_SI=0.825e-12/160'"

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_DT_SI=0.825e-12/80'"
  flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_DT_SI=0.825e-12/40'"
  flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_DT_SI=0.825e-12/20'"
  flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_DT_SI=0.825e-12/10'"
fi

################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
