#!/usr/bin/env bash

# SPDX-FileCopyrightText: Axel Huebl, Rene Widera
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

# default case is "-DPARAM_OVERWRITES:LIST='-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLESHAPE=TSC'"
flags[0]=""

# limit examles if we run CI tests
if [ -z  "$PIC_CI_MAINLINE" ] ; then
  flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLESHAPE=TSC'"
  flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_PRECISION=precision32Bit;-DPARAM_PARTICLESHAPE=PQS'"
fi
# Depending on the GPU vendor and version compile can fail because of limited amound of shared memory.
# Please enable the test by hand!
# flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_PRECISION=precision64Bit;-DPARAM_PARTICLESHAPE=PQS'"

################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
