# SPDX-FileCopyrightText: PIConGPU contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
This file is part of PIConGPU.
Copyright 2021-2024 PIConGPU contributors
Authors: Hannes Troepgen, Brian Edward Marre
License: GPLv3+
"""

from pydantic import BaseModel

from ...rendering import RenderedObject


class Constant(RenderedObject, BaseModel):
    """
    unmodifiable property of a species

    Equal for all macroparticles, e.g. mass, charge, ionization levels etc.
    Owned by **exactly one** species.

    PIConGPU term: "particle flags"

    Parent class for actual SpeciesConstants

    A Constant can have the following dependencies:

    - species objects

        - dependency species must be available for the init manager
        - code for dependency species will be generated *before* the code for
          this species

    - attributes (types)

        - dependency attributes must be generated by *any* property on the
          species with this constant
        - there are no further checks employed, the constant is never shown the
          concrete attribute object of its species

    - constants (types)

        - dependency constants must be present before the initmanager performs
          any actions
        - checks on the value of constants are not possible, only if a constant
          of a given type is present
        - (the concrete constant that is being checked is never passed to this
          constant)
    """

    def check(self):
        pass
