Bootstrap: docker
From: computationalradiationphysics/picongpu:0.6.0-dev


%labels
Maintainer "Axel Huebl <a.huebl@hzdr.de>, Rene Widera <r.widera@hzdr.de>"
Version 0.6.0-dev


%runscript
exec /bin/bash -l
